method: dynamic_planes_conv_onet
data:
  classes: ['rooms_04', 'rooms_05', 'rooms_06', 'rooms_07', 'rooms_08']
  input_type: pointcloud
  path: ../../hazh_dataset
  pointcloud_n: 10000
  pointcloud_noise: 0.05
  points_subsample: 2048
  points_file: points_iou
  points_iou_file: points_iou
  pointcloud_file: pointcloud
  pointcloud_chamfer_file: pointcloud
  multi_files: 10
  voxels_file: null
  overfit: False
  overfit_num: 0
  padding: 0.1
model:
  encoder_latent: null
  decoder: dynamic_simple_local
  encoder: dynamic_pointnet_local_pool
  encoder_kwargs:
    hidden_dim: 32
    plane_resolution: 128
    unet: False
    unet_kwargs:
      depth: 5
      merge_mode: concat
      start_filts: 32
    n_channels: 3
    pos_encoding: False
    plane_net: FCPlanenet
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
    pos_encoding: False
  c_dim: 32
  z_dim: 0
training:
  out_dir: out/pointcloud/room_3plane_dynamic/
  batch_size: 2
  similarity: True
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 200
  visualize_every: 200
  validate_every: 200
  checkpoint_every: 200
  backup_every: 1000
  n_workers: 2
  n_workers_val: 2
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  #model_file: /home/alcor/students/melis_tonti/new_model/out/pointcloud/shapenet_dynamic_3plane_final/model_best.pt
  model_file: /home/alcor/students/melis_tonti/phd_model/out/pointcloud/room_3plane_dynamic/model_best.pt
  #model_file: /home/alcor/students/melis_tonti/phd_model/out/pointcloud/room_3plane_dynamic/d4_b16_644.175G_1.761M/model_best.pt
generation:
  batch_size: 100000
  vis_n_outputs: 2
  # resolution_0: 64
  refine: false
  n_x: 128
  n_z: 1

degrees : 0