method: dynamic_planes_conv_onet
data:
  classes: ['rooms_04', 'rooms_05', 'rooms_06', 'rooms_07', 'rooms_08']
  input_type: pointcloud
  path: data/RoomDataset5
  pointcloud_n: 10000
  pointcloud_noise: 0.005
  points_subsample: 2048
  points_file: points_iou
  points_iou_file: points_iou
  pointcloud_file: pointcloud
  pointcloud_chamfer_file: pointcloud
  multi_files: 10
  voxels_file: null
  overfit: False
  overfit_num: 0
  padding: 0.1
model:
  encoder_latent: null
  decoder: dynamic_simple_local
  encoder: dynamic_pointnet_local_pool
  encoder_kwargs:
    hidden_dim: 32
    plane_resolution: 128
    unet: True
    unet_kwargs:
      depth: 5
      merge_mode: concat
      start_filts: 32
    n_channels: 3
    pos_encoding: True
    plane_net: FCPlanenet
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
    pos_encoding: False
  c_dim: 32
  z_dim: 0
training:
  out_dir: out/pointcloud/room_3plane_dynamic
  batch_size: 2
  similarity: True
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 100
  visualize_every: 10000
  validate_every: 10000
  checkpoint_every: 2000
  backup_every: 10000
  n_workers: 8
  n_workers_val: 4
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: room_3plane_dynamic_best.pt
generation:
  batch_size: 100000
  vis_n_outputs: 2
  # resolution_0: 64
  refine: false
  n_x: 128
  n_z: 1

degrees : 0