method: dynamic_planes_conv_onet
data:
  input_type: pointcloud
  classes: null
  input_type: pointcloud
  path: ../dataset/
  watertight_path: ../watertight
  pointcloud_n: 3000
  pointcloud_noise: 0.005
  points_subsample: 2048
  points_file: points.npz
  points_iou_file: points.npz
  # points_unpackbits: false
  voxels_file: null
  padding: 0.1
model:
  encoder_latent: null
  decoder: dynamic_simple_local
  encoder: dynamic_pointnet_local_pool
  encoder_kwargs:
    hidden_dim: 32
    plane_resolution: 32
    unet: False
    unet_kwargs:
      depth: 3
      merge_mode: concat
      start_filts: 32
    n_channels: 3
    pos_encoding: False
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
    pos_encoding: False
  c_dim: 32
  z_dim: 0
training:
  out_dir: out/pointcloud/shapenet_dynamic_3plane_final
  batch_size: 64
  similarity: True
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 200
  visualize_every: 200
  validate_every: 200
  checkpoint_every: 200
  backup_every: 200
  n_workers: 4
  n_workers_val: 2
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: /out/pointcloud/shapenet_dynamic_3plane_final/model_best.pt
  #model_file: None
generation:
  batch_size: 100000
  vis_n_outputs: 2
  # resolution_0: 64
  refine: false
  n_x: 128
  n_z: 1